export const GET_PRODUCT_DATA_REQUEST = "GET_PRODUCT_DATA_REQUEST";
export const GET_PRODUCT_DATA_SUCCESS = "GET_PRODUCT_DATA_SUCCESS";
export const GET_PRODUCT_DATA_FAILURE = "GET_PRODUCT_DATA_FAILURE";

export const ADD_TO_CART=  "ADD_TO_CART";
export const DELTE_CART_ITEM = "DELETE_CART_ITEM"
