// export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
// export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";
// export const NOTIFICATION_WARNING = "NOTIFICATION_WARNING";


export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

